### ISSUE TITLE
FAQ: what differs kyt from Roc?

### ISSUE THREAD

**Issue by fatso83** [NYTimes/kyt#154]
Congrats on shipping this. I was just wondering what differs this project from [Roc](http://www.getroc.org), which I found a few months ago. The [article on open](http://open.blogs.nytimes.com/2016/09/13/introducing-kyt-our-web-app-configuration-toolkit) seems to want to solve the same set of problems as the creators of Roc [sets out in this article](https://medium.com/@DZV/roc-one-solution-to-javascript-fatigue-b14ea07b9763). Maybe the latter is trying to solve a bigger problem. Not quite sure, but maybe trying to unite forces could be an idea given the similarities.

**Comment by delambo** [comment]
Thanks for pointing this out! Sorry, we were not aware of Roc. I think the biggest difference is that Roc has a nice website ✨ ! But there is one important difference that I gathered from skimming the site, which is that kyt aims to not depend on React. In fact, kyt is designed to give users the freedom to include whatever frameworks they need in their source directory. Angular2, Backbone, or JQuery with server rendered Mustache templates should all work well next to kyt. As an example, I created a [WIP Angular2 starter-kyt](https://github.com/delambo/kyt-starter-universal-angular2). If this is also a feature of Roc, please let me know.

We'll add it to the FAQ, possibly in the form of a "Similar Projects" section. Thanks!

**Comment by fatso83** [comment]
Actually, that's one of the main features of Roc as well :-)

> Not be opinionated in the sense that it can only do one thing, e.g React, Mocha, but should work with whatever is the best tool for the job through a modular and extendable architecture.
([source](https://medium.com/@arsovik/rethinking-modern-javascript-development-6aee92b860aa#.a0b18gpmf))

It is basically a way of sharing  "library composition patterns ready for immediate consumption" (from [this background article](https://medium.com/@arsovik/rethinking-modern-javascript-development-6aee92b860aa#.a0b18gpmf)). 

I guess it's just another case of [multiple discovery](https://en.wikipedia.org/wiki/Multiple_discovery), in the aftermath of the javascript fatigue discussions. And since the developers making Roc are backed by a big newspaper company with a lot of interactive publications I guess it's no wonder that they faced struggles that were similar to yours 😄  The more the merrier!

P.S. I am not in the dev team or associated. I just saw it presented on a [Meeup a few months ago](https://www.meetup.com/framsia/events/229406512/) and thought this seemed very similar.

**Comment by delambo** [comment]
Ah, thanks for the clarification. I should have looked into it more. The site really makes it look like React is a dependency.

**Comment by dlmr** [comment]
Hello, one of the developers behind Roc here! 👋 

As @fatso83 mentions seems like we have very similar goals and collaboration would most likley be beneficial for us both. It is quite obvious that our projects are born out of the same pain points, especially since we are both tackling the problem space from a publisher perspective! 😄 

First of all, the site ([getroc.org](http://getroc.org)) does not accurately reflect the current state of Roc in a good way and we will update it in the near future. React has been one of the focus for us but Roc is at its core **totally agnostic** for any frameworks or libraries. 

One example of this is that Roc is not coupled with Webpack for example and other alternatives can easily be added like Browserify and Rollup. The core of Roc is really more like a framework for creating solutions like kyt, create-react-app and similar. It defines a way to create something that we call `extensions` that can define custom commands, settings, something we call actions/hooks ([similar](https://github.com/rocjs/roc-package-webpack/blob/next/extensions/roc-package-webpack-dev/docs/Hooks.md#build-webpack) to `modifyWebpackConfig` that exists in kyt) and much more. These extensions are also composable meaning that one extension can for instance add basic Webpack configuration (https://github.com/rocjs/roc-package-webpack/) and then another can add what is need for React projects (https://github.com/rocjs/roc-package-web-app-react/). This also means that the testing boilerplate is provided in something we call a `plugin` meaning that it is an easily replaceable part making it possible to provide several different solutions like Ava and Jest. We currently have test plugin that support Mocha and Karma https://github.com/rocjs/roc-plugin-test-mocha-karma-webpack/ that adds a test command.

This means that a Roc project does not have a direct dependency on Roc itself but rather on a `package` that can be a composition of several other `extensions` that together brings exactly what the developer need for the current project and with the option to add plugins that brings additional features in a plug-and-play manner. An example of this is that the modifications that are done to the Webpack configuration in the [Angular2 starter-kyt](https://github.com/delambo/kyt-starter-universal-angular2) is boilerplate in kyt where this could be a package in Roc that can be reused for several projects and updated without the user needing to do manual changes. Roc supports several way to make this dynamic behaviour easy for the developer, featuring a dynamic command line interface and documentation generation for almost all aspects of the setup to mention something.

We are about to land the next version of Roc that will bring several improvments to it along with new documentation. A good place to start can be seen here https://github.com/rocjs/roc/blob/next/docs/Introduction.md

I hope that we can help each other to make the experience when creating JavaScript projects as good as possible.

**Comment by ccpricenytimes** [comment]
Awesome to hear more about Roc. 

Going to close this in favor of #160 

Thanks!
