### ISSUE TITLE
Releases are out of sync

### ISSUE THREAD

**Issue by mrmckeb** [NYTimes/kyt#175]
Hi there, 

There seem to be two issues with the current release process:
1. Releases on GitHub don't seem to align with releases on npm.
2. Starter kits aren't versioned, but have dependencies in kyt (for example, right now the current npm release of kyt has AVA, but the starter kits are already using Jest for tests). For now we've worked around this by installing directly from this repository instead of via npm, and tests run - but then that seems to break the the dev server.

**Comment by delambo** [comment]
Yes, very sorry about that. We're trying to find the right balance on updating the starter-kyt dependencies. We're about to cut a 0.2.0 release which has quite a few breaking changes. After that we'll update the starter-kyts so that they reflect all of the new changes and include an update that will pin them to the current npm kyt version. I created a new issue for these tasks #176.

Sorry for the trouble!

**Comment by delambo** [comment]
Hey @mrmckeb - We published 0.2.0 and updated the starter-kyts. Thanks for pointing this out.

**Comment by mrmckeb** [comment]
Thanks @delambo - and sorry for not replying earlier, I'd just gotten back from overseas and got snowed under.

I'll give the updates a go on Monday morning, great work on this, we've already found it very useful and mixed Redux in seamlessly.

**Comment by delambo** [comment]
Cool. We're thinking about creating a Redux starter-kyt. There's some discussion over [here](https://github.com/NYTimes/kyt-starter-universal/issues/10). I would love your input on the shared    repository, as we might build something like that.
