### ISSUE TITLE
Support plugin/preset definitions without prefixes in .babelrc

### ISSUE THREAD

**Issue by zdoc01** [NYTimes/kyt#303]
We currently cannot specify babel plugins and presets without the `babel-*` prefix in `config/babel.js` because of the way they are resolved. This is a standard convention that's highlighted in the babel docs for a given plugin or preset (see [these babel-preset-react docs](https://babeljs.io/docs/plugins/preset-react/#usage) as an example).

**Comment by zdoc01** [comment]
It would also be awesome if this issue had a 'hacktoberfest' label :).

**Comment by tizmagik** [comment]
Good catch, +1 from me on this issue 👍

**Comment by tizmagik** [comment]
Although this _might_ be moot depending on where we land with #250 / #134 but this might be good to get in in the mean time. @delambo thoughts?

**Comment by delambo** [comment]
You're right @tizmagik, this will most likely be moot when 0.4.0 comes out since we're leaning on the monorepo/babel plugin [pull request](https://github.com/NYTimes/kyt/issues/250) that @jaredmcdonald is working on. Let's merge this change and release it in 0.3.1 in case users bump up against this problem in the interim.

**Comment by jaredmcdonald** [comment]
we'll probably need to do something like this when we support user `.babelrc`s anyway, so I can port what @zdoc01 did here 👍
