### ISSUE TITLE
ESLint in editor (Atom) not working

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#437]
### Bug or Feature?
Bug

### Current Behavior
![image](https://cloud.githubusercontent.com/assets/244704/23824293/d119cab0-0641-11e7-9cf0-c45d84c8805f.png)

### Desired Behavior
ESLint in editor works.

Noticed this in Atom, have not seen/tried other editors.

**Comment by delambo** [comment]
I think this is because we're using the eslint dependencies in kyt-core. My original idea was to dog-food kyt-core's linter and keep the dependencies in one place but if we want our text editors to lint we'll have to additionally manage the eslint dependencies in the root package.json [sigh]. 

Unfortunately, lerna won't help us with this since it only hoists common devDependencies to the top level but let me know if I'm wrong because I've been thinking about a spike on lerna.

**Comment by tizmagik** [comment]
Yea, lerna wouldn't help here, but I think managing the eslint dependencies in the root of package.json wouldn't be so bad right? Isn't it just a matter of adding eslint, eslint-config-airbnb et al to devDependencies?

**Comment by delambo** [comment]
Yeah, it's not terrible, I'm just being overly idealistic. Since we're in the game of dependency management and we're pretty aggressive about updates I thought it would be simpler to maintain things in one place. NBD.

**Comment by delambo** [comment]
This works now since we use lerna to hoist everything to the root on bootstrap.
