### ISSUE TITLE
Touch icons and favicon.ico

### ISSUE THREAD

**Issue by joergklein** [NYTimes/kyt#492]
How and in which directory should be the favicon.ico and the touch icons? In
/src/public? Or mybe better /src/images/icon? Is it possible to send me some
lines of code? Is the static folder a good idea? It looks like a subdomain?

The page from the New York Times has this folder and icons.
```
<link rel="shortcut icon" href="https://static01.nyt.com/favicon.ico" />
<link rel="apple-touch-icon-precomposed" sizes="144×144" href="https://static01.nyt.com/images/icons/ios-ipad-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="114×114" href="https://static01.nyt.com/images/icons/ios-iphone-114x144.png" />
<link rel="apple-touch-icon-precomposed" href="https://static01.nyt.com/images/icons/ios-default-homescreen-57x57.png" />
```

Do I need all this Touch icons?

Size                   | Name
--------------------|-----------------
16x16 & 32x32  | favicon.ico
32x32                | favicon-32.png
57x57                | favicon-57.png
76x76                | favicon-76.png
96x96                | favicon-96.png
120x120            | favicon-120.png
128x128            | favicon-128.png
128x128            | smalltile.png
144x144            | favicon-144.png
152x152            | favicon-152.png
180x180            | favicon-180.png
195x195            | favicon-195.png
196x196            | favicon-196.png
228x228            | favicon-228.png
270x270            | mediumtile.png
558x270            | widetile.png

**Comment by jaredmcdonald** [comment]
hey @joergklein, maybe this thread will help: https://github.com/h5bp/html5-boilerplate/issues/1367.

you can put your static assets wherever you want, here's how you configure that in express: https://expressjs.com/en/starter/static-files.html. [by default we use `src/public`](https://github.com/NYTimes/kyt/blob/e447e9c0fe480d6cd5a777bacf20bc777363f0b0/docs/conventions.md#public-directory) but you could put whatever subdirectories you want inside that.

i'm going to close this because it doesn't really have anything to do with kyt, but hopefully those links help!
