### ISSUE TITLE
css styles

### ISSUE THREAD

**Issue by joergklein** [NYTimes/kyt#493]
How do I bind a navbar for header and footer with a dropdown menu?
The site should be responsive and equally suitable for mobile devices.
On my old homepage I used Twitter Bootstrap. What's your
Recommendation? What solution do you use in the New York Times?

**Comment by jaredmcdonald** [comment]
@joergklein - there's no reason you couldn't continue using Bootstrap with kyt (and React, or Angular, or whatever); in some places, we're using [https://github.com/reactjs/react-modal](react-modal) for dropdowns/modals. kyt is really just a build system and you can do whatever you'd like with it - you could use kyt to package up a Bootstrap site, or a React application, or a static HTML file with some frontend scripts.

here's a decent forum on css-tricks about responsive fixed headers: https://css-tricks.com/forums/topic/responsive-fixed-header-with-css/

closing since this isn't really a question about kyt itself, but let me know if i can point you toward any other resources, etc.
