### ISSUE TITLE
Generated classnames contain 'styles' prefix

### ISSUE THREAD

**Issue by janhoogeveen** [NYTimes/kyt#514]
### Versions of kyt, node, OS
Kyt v0.7.0
Node v8.1.2
NPM v5.3.0

### Bug or Feature?
Bug-ish

### Current Behavior
CSS Modules stylenames are getting the 'styles-' prefix in DOM output. I've never seen CSS-modules do this. 

![screen shot 2017-07-25 at 09 52 02](https://user-images.githubusercontent.com/882219/28561677-a12e4166-711f-11e7-98ff-eebbe6cb86be.png)

### Desired Behavior

Instead of
`styles-LoginForm--382l8`

I'd expect to see
`LoginForm--382l8`

as the generated classname.

Worth mentioning is that the style filenames are `styles.scss`.

**Comment by tizmagik** [comment]
This is because of how the `localIdentName` is [specified](https://github.com/NYTimes/kyt/blob/master/packages/kyt-core/config/webpack.dev.client.js#L14):

```
localIdentName: '[name]-[local]--[hash:base64:5]'
```

So it uses the filename then the "local" className then a hash. You could change this in your `modifyWebpackConfig()` or change the scss filename to match the component name.

**Comment by janhoogeveen** [comment]
Got it! Thanks for that!
