### ISSUE TITLE
No PostCSS Config found when running `npm run proto`

### ISSUE THREAD

**Issue by IonCaza** [nytimes/kyt#567]
### Versions of kyt, node, OS
Latest on universal kit, Mac OS X High Sierra

### Bug
When running `npm run proto` I get the following error

Module build failed: Error: No PostCSS Config found in: /.../src/components/Home

### Desired Behavior
Proto works :)

**Comment by joshourisman** [comment]
I am encountering the same problem running Kyt in a Docker container using the official node:8. If I duplicate Kyt's postcss.config.js, I get a different error about not having the appropriate loader.

```
ERROR in ./node_modules/kyt/prototype/index.html
Module parse failed: /workspaces/itinerary/node_modules/kyt/prototype/index.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <div id="root"></div>
| <script src="/prototype/bundle.js"></script>
| 
 @ multi react-hot-loader/patch webpack/hot/dev-server webpack-dev-server/client?http://localhost:3002 ./node_modules/kyt/prototype/index.html ./prototype.js
webpack: Failed to compile.
```

**Comment by joshourisman** [comment]
It looks like the initial problem is due to changes to the dev and prod webpack configs that weren't carried over to the proto webpack config. Specifically, the way the postcssLoader is configured is different. Updating the webpack.proto.js to load the postcss loader the same way it does in webpack.dev.client.js accomplishes the same thing adding a new, top-level postcss.config.js as in my previous comment, but also retains that same error, so it's only part of the solution.

**Comment by staylor** [comment]
`kyt proto` has since been deprecated: https://github.com/nytimes/kyt/pull/639
