### ISSUE TITLE
Display gzip size with Assets output on build

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#57]
Would be nice to also show gzip size along with the assets output:

```
641.23 KB    (178  KB gzip)   build/client/main-618bbd3a04be91bfc336.js
164.22 KB    (23.5 KB gzip)   build/client/main-3e90752ad5a140255589.css
```

Can use [gzip-size](https://github.com/sindresorhus/gzip-size)

**Comment by dting** [comment]
@tizmagik I'd like to take a crack at this change if no one has claimed it. 

I have it working where it reads the files and displays the gzip size without creating the .gz assets. I'll make a PR if this is still a desired change.

**Comment by ccpricenytimes** [comment]
Awesome @dting Thanks!

**Comment by tizmagik** [comment]
Sounds good! I'm not sure if the .gz files are desirable or not, I guess it depends on people's pipelines. @delambo ?

**Comment by delambo** [comment]
We'll leave it out for now. It can be easily added by users. Maybe later we should add that to a guide or best practices section in the readme. Thanks @dting.

**Comment by dting** [comment]
Cool, thanks! I made the PR let me know if any changes are needed. 

I wasn't sure how to get the path to the files so I passed in the `clientConfig` to the function. Is there a prefered method?

Also, the output is also right padded around the entire labels instead of in between the number and the storage size unit. The current code is right padded but I can split the labels from `filesize` and rejoin to match the example from the original issue:

```
ℹ️  Assets:
    191.11 KB    (56.29 KB gzip)    build/public/main-711be476def76eea5fe9.js
    6.25 KB      (3.33 KB gzip)     build/public/main-4d956c54defd131d453a.css
    1.47 KB      (620 B gzip)       build/public/0-bd3ca39a5fbaaea26357.js
    1.02 KB      (569 B gzip)       build/public/1-edf2f67fb192eca315c5.js
```

vs

```
ℹ️  Assets:
    191.11 KB    (56.29 KB gzip)    build/public/main-711be476def76eea5fe9.js
    6.25   KB    (3.33  KB gzip)    build/public/main-4d956c54defd131d453a.css
    1.47   KB    (620    B gzip)    build/public/0-bd3ca39a5fbaaea26357.js
    1.02   KB    (569    B gzip)    build/public/1-edf2f67fb192eca315c5.js
```
